package view;

import dao.AppointmentDAO;
import dao.DentistDAO;
import dao.PatientDAO;
import model.Appointment;
import model.Dentist;
import model.Patient;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.Map;

/**
 * Appointment Scheduling GUI Form
 * Fully compatible with NetBeans GUI Builder Design View
 */
public class AppointmentForm extends javax.swing.JFrame {

    private final AppointmentDAO appointmentDAO = new AppointmentDAO();
    private final PatientDAO patientDAO = new PatientDAO();
    private final DentistDAO dentistDAO = new DentistDAO();
    private final JFrame parentDashboard;
    private DefaultTableModel tableModel;

    public AppointmentForm() {
        this(null);
    }

    public AppointmentForm(JFrame parentDashboard) {
        this.parentDashboard = parentDashboard;
        initComponents();
        UITheme.setFrameIcon(this);
        
        // Setup icons
        btnSave.setIcon(UITheme.getIcon("add.png", 16, 16));
        btnUpdate.setIcon(UITheme.getIcon("edit.png", 16, 16));
        btnDelete.setIcon(UITheme.getIcon("delete.png", 16, 16));
        btnClear.setIcon(UITheme.getIcon("clear.png", 16, 16));
        btnSearch.setIcon(UITheme.getIcon("search.png", 16, 16));
        btnResetSearch.setIcon(UITheme.getIcon("refresh.png", 16, 16));
        btnProceedToBilling.setIcon(UITheme.getIcon("billing.png", 16, 16));
        btnBack.setIcon(UITheme.getIcon("back.png", 16, 16));
        
        tableModel = (DefaultTableModel) tblAppointments.getModel();
        UITheme.styleTable(tblAppointments);
        loadPatientsCombo();
        loadDentistsCombo();
        loadTreatmentsCombo();
        loadAppointmentData();
        generateNewAppointmentNo();
        
        cmbPatient.addActionListener(e -> checkPatientDoctorRecommendations());
    }

    private void checkPatientDoctorRecommendations() {
        Object pObj = cmbPatient.getSelectedItem();
        if (pObj instanceof PatientComboItem) {
            PatientComboItem p = (PatientComboItem) pObj;
            Appointment rec = appointmentDAO.getLatestRecommendationForPatient(p.id);
            if (rec != null && rec.getRecommendedTreatment() != null && !rec.getRecommendedTreatment().isEmpty()) {
                for (int i = 0; i < cmbTreatment.getItemCount(); i++) {
                    Object tObj = cmbTreatment.getItemAt(i);
                    if (tObj instanceof TreatmentComboItem && ((TreatmentComboItem) tObj).name.equalsIgnoreCase(rec.getRecommendedTreatment())) {
                        cmbTreatment.setSelectedIndex(i);
                        break;
                    }
                }
                txaNotes.setText("Doctor's Recommendation (" + rec.getDentistName() + "): " + rec.getRecommendedTreatment() + " [" + rec.getFollowUpAdvice() + "]");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        formCard = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        lblApptNo = new javax.swing.JLabel();
        txtAppointmentNo = new javax.swing.JTextField();
        lblPatient = new javax.swing.JLabel();
        cmbPatient = new javax.swing.JComboBox<>();
        lblDentist = new javax.swing.JLabel();
        cmbDentist = new javax.swing.JComboBox<>();
        lblTreatment = new javax.swing.JLabel();
        cmbTreatment = new javax.swing.JComboBox<>();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        lblTime = new javax.swing.JLabel();
        cmbTimeSlot = new javax.swing.JComboBox<>();
        lblStatus = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        lblNotes = new javax.swing.JLabel();
        jScrollPaneNotes = new javax.swing.JScrollPane();
        txaNotes = new javax.swing.JTextArea();
        lblEstimatedCost = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnProceedToBilling = new javax.swing.JButton();
        tableCard = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnResetSearch = new javax.swing.JButton();
        jScrollPaneTable = new javax.swing.JScrollPane();
        tblAppointments = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sunrise Dental Clinic - Appointment Scheduling");

        headerPanel.setBackground(new java.awt.Color(15, 118, 110));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_48.png"))); // NOI18N

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("APPOINTMENT REGISTRATION & SCHEDULING");

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnBack.setText("⬅ Back to Dashboard");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitle)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        formCard.setBackground(new java.awt.Color(255, 255, 255));
        formCard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 232, 240), 1, true));

        lblHeading.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblHeading.setText("Schedule Appointment");

        lblApptNo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblApptNo.setText("Appt No:");

        txtAppointmentNo.setEditable(false);
        txtAppointmentNo.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        lblPatient.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblPatient.setText("Patient *:");

        lblDentist.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblDentist.setText("Dentist *:");

        cmbDentist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDentistActionPerformed(evt);
            }
        });

        lblTreatment.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTreatment.setText("Treatment *:");

        cmbTreatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTreatmentActionPerformed(evt);
            }
        });

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblDate.setText("Date:");

        txtDate.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        lblTime.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTime.setText("Time Slot:");

        cmbTimeSlot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09:00 AM", "09:30 AM", "10:00 AM", "10:30 AM", "11:00 AM", "11:30 AM", "02:00 PM", "02:30 PM", "03:00 PM", "03:30 PM", "04:00 PM", "04:30 PM", "05:00 PM" }));

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblStatus.setText("Status:");

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Scheduled", "Confirmed", "Completed", "Cancelled" }));

        lblNotes.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblNotes.setText("Notes:");

        txaNotes.setColumns(14);
        txaNotes.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txaNotes.setLineWrap(true);
        txaNotes.setRows(2);
        txaNotes.setWrapStyleWord(true);
        jScrollPaneNotes.setViewportView(txaNotes);

        lblEstimatedCost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEstimatedCost.setForeground(new java.awt.Color(15, 118, 110));
        lblEstimatedCost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstimatedCost.setText("Est. Fee: LKR 0.00");

        btnSave.setBackground(new java.awt.Color(15, 118, 110));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Book");
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(239, 68, 68));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnProceedToBilling.setBackground(new java.awt.Color(37, 99, 235));
        btnProceedToBilling.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnProceedToBilling.setForeground(new java.awt.Color(255, 255, 255));
        btnProceedToBilling.setText("💳 Proceed to Billing");
        btnProceedToBilling.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProceedToBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedToBillingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formCardLayout = new javax.swing.GroupLayout(formCard);
        formCard.setLayout(formCardLayout);
        formCardLayout.setHorizontalGroup(
            formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formCardLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeading)
                    .addGroup(formCardLayout.createSequentialGroup()
                        .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApptNo)
                            .addComponent(lblPatient)
                            .addComponent(lblDentist)
                            .addComponent(lblTreatment)
                            .addComponent(lblDate)
                            .addComponent(lblTime)
                            .addComponent(lblStatus)
                            .addComponent(lblNotes))
                        .addGap(18, 18, 18)
                        .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPaneNotes, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(cmbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbTimeSlot, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDate)
                            .addComponent(cmbTreatment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbDentist, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbPatient, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAppointmentNo)))
                    .addComponent(lblEstimatedCost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formCardLayout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProceedToBilling, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        formCardLayout.setVerticalGroup(
            formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formCardLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApptNo)
                    .addComponent(txtAppointmentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatient)
                    .addComponent(cmbPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDentist)
                    .addComponent(cmbDentist, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTreatment)
                    .addComponent(cmbTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime)
                    .addComponent(cmbTimeSlot, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNotes)
                    .addComponent(jScrollPaneNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEstimatedCost, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProceedToBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tableCard.setBackground(new java.awt.Color(255, 255, 255));
        tableCard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 232, 240), 1, true));

        lblSearch.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblSearch.setText("Search Appt:");

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnResetSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnResetSearch.setText("Reset");
        btnResetSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResetSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetSearchActionPerformed(evt);
            }
        });

        tblAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Appt No", "Patient ID", "Patient Name", "Dentist", "Treatment", "Date", "Time", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAppointments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAppointmentsMouseClicked(evt);
            }
        });
        jScrollPaneTable.setViewportView(tblAppointments);

        javax.swing.GroupLayout tableCardLayout = new javax.swing.GroupLayout(tableCard);
        tableCard.setLayout(tableCardLayout);
        tableCardLayout.setHorizontalGroup(
            tableCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableCardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(tableCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addGroup(tableCardLayout.createSequentialGroup()
                        .addComponent(lblSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResetSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );
        tableCardLayout.setVerticalGroup(
            tableCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableCardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(tableCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneTable, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(formCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tableCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(formCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadPatientsCombo() {
        cmbPatient.removeAllItems();
        List<Patient> patients = patientDAO.getAllPatients();
        for (Patient p : patients) {
            cmbPatient.addItem(new PatientComboItem(p.getPatientId(), p.getName(), p.getContactNo()));
        }
    }

    private void loadDentistsCombo() {
        cmbDentist.removeAllItems();
        List<Dentist> dentists = dentistDAO.getAllDentists();
        for (Dentist d : dentists) {
            cmbDentist.addItem(new DentistComboItem(d.getName(), d.getSpecialization(), d.getConsultationFee()));
        }
    }

    private void loadTreatmentsCombo() {
        cmbTreatment.removeAllItems();
        Map<String, Double> treatments = dentistDAO.getAllTreatmentsWithCosts();
        for (Map.Entry<String, Double> entry : treatments.entrySet()) {
            cmbTreatment.addItem(new TreatmentComboItem(entry.getKey(), entry.getValue()));
        }
        updateCostPreview();
    }

    private void updateCostPreview() {
        double consultFee = 0.0;
        double treatCost = 0.0;

        Object dObj = cmbDentist.getSelectedItem();
        if (dObj instanceof DentistComboItem) {
            consultFee = ((DentistComboItem) dObj).consultationFee;
        }

        Object tObj = cmbTreatment.getSelectedItem();
        if (tObj instanceof TreatmentComboItem) {
            treatCost = ((TreatmentComboItem) tObj).cost;
        }

        double total = consultFee + treatCost;
        lblEstimatedCost.setText("Est. Total: LKR " + String.format("%,.2f", total));
    }

    public void generateNewAppointmentNo() {
        txtAppointmentNo.setText(appointmentDAO.generateNextAppointmentNo());
    }

    public void loadAppointmentData() {
        tableModel.setRowCount(0);
        List<Appointment> list = appointmentDAO.getAllAppointments();
        for (Appointment a : list) {
            tableModel.addRow(new Object[]{
                    a.getAppointmentNo(),
                    a.getPatientId(),
                    a.getPatientName(),
                    a.getDentistName(),
                    a.getTreatmentType(),
                    a.getAppointmentDate(),
                    a.getAppointmentTime(),
                    a.getStatus()
            });
        }
    }

    private void cmbDentistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDentistActionPerformed
        updateCostPreview();
    }//GEN-LAST:event_cmbDentistActionPerformed

    private void cmbTreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTreatmentActionPerformed
        updateCostPreview();
    }//GEN-LAST:event_cmbTreatmentActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String apptNo = txtAppointmentNo.getText().trim();
        Object patientObj = cmbPatient.getSelectedItem();
        Object dentistObj = cmbDentist.getSelectedItem();
        Object treatmentObj = cmbTreatment.getSelectedItem();
        String dateStr = txtDate.getText().trim();
        String timeSlot = (String) cmbTimeSlot.getSelectedItem();
        String status = (String) cmbStatus.getSelectedItem();
        String notes = txaNotes.getText().trim();

        if (patientObj == null || dentistObj == null || treatmentObj == null || dateStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all mandatory fields!", "Validation Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        PatientComboItem patientItem = (PatientComboItem) patientObj;
        DentistComboItem dentistItem = (DentistComboItem) dentistObj;
        TreatmentComboItem treatmentItem = (TreatmentComboItem) treatmentObj;

        Date sqlDate;
        try {
            sqlDate = Date.valueOf(dateStr);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Invalid Date format! Use YYYY-MM-DD.", "Date Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (appointmentDAO.isDoubleBooked(dentistItem.name, sqlDate, timeSlot, null)) {
            JOptionPane.showMessageDialog(this,
                    "Conflict: " + dentistItem.name + " is already booked on " + sqlDate + " at " + timeSlot + "!",
                    "Double Booking Conflict",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        Appointment appt = new Appointment(apptNo, patientItem.id, patientItem.name, dentistItem.name, treatmentItem.name, sqlDate, timeSlot, status, notes);
        boolean success = appointmentDAO.createAppointment(appt);

        if (success) {
            JOptionPane.showMessageDialog(this, "Appointment " + apptNo + " confirmed for " + patientItem.name + "!", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadAppointmentData();
            btnClearActionPerformed(evt);
            if (parentDashboard instanceof Dashboard) {
                ((Dashboard) parentDashboard).loadDashboardStatistics();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Failed to schedule appointment.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String apptNo = txtAppointmentNo.getText().trim();
        Object patientObj = cmbPatient.getSelectedItem();
        Object dentistObj = cmbDentist.getSelectedItem();
        Object treatmentObj = cmbTreatment.getSelectedItem();
        String dateStr = txtDate.getText().trim();
        String timeSlot = (String) cmbTimeSlot.getSelectedItem();
        String status = (String) cmbStatus.getSelectedItem();
        String notes = txaNotes.getText().trim();

        if (apptNo.isEmpty() || patientObj == null || dentistObj == null || treatmentObj == null) {
            JOptionPane.showMessageDialog(this, "Please select an appointment from the table to update!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        PatientComboItem patientItem = (PatientComboItem) patientObj;
        DentistComboItem dentistItem = (DentistComboItem) dentistObj;
        TreatmentComboItem treatmentItem = (TreatmentComboItem) treatmentObj;

        Date sqlDate;
        try {
            sqlDate = Date.valueOf(dateStr);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Invalid Date format! Use YYYY-MM-DD.", "Date Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (appointmentDAO.isDoubleBooked(dentistItem.name, sqlDate, timeSlot, apptNo)) {
            JOptionPane.showMessageDialog(this, "Conflict: Dentist already booked at this time slot!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Appointment appt = new Appointment(apptNo, patientItem.id, patientItem.name, dentistItem.name, treatmentItem.name, sqlDate, timeSlot, status, notes);
        boolean success = appointmentDAO.updateAppointment(appt);

        if (success) {
            JOptionPane.showMessageDialog(this, "Appointment updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadAppointmentData();
            btnClearActionPerformed(evt);
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update appointment.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String apptNo = txtAppointmentNo.getText().trim();
        if (apptNo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select an appointment to delete!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to cancel appointment " + apptNo + "?", "Confirm Cancel", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            boolean success = appointmentDAO.deleteAppointment(apptNo);
            if (success) {
                JOptionPane.showMessageDialog(this, "Appointment cancelled.", "Deleted", JOptionPane.INFORMATION_MESSAGE);
                loadAppointmentData();
                btnClearActionPerformed(evt);
                if (parentDashboard instanceof Dashboard) {
                    ((Dashboard) parentDashboard).loadDashboardStatistics();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete appointment.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        generateNewAppointmentNo();
        txtDate.setText(new SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()));
        cmbTimeSlot.setSelectedIndex(0);
        cmbStatus.setSelectedIndex(0);
        txaNotes.setText("");
        tblAppointments.clearSelection();
        updateCostPreview();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnProceedToBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedToBillingActionPerformed
        String apptNo = txtAppointmentNo.getText().trim();
        if (apptNo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select an appointment first!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        BillingForm billingForm = new BillingForm(parentDashboard != null ? parentDashboard : this, apptNo);
        billingForm.setVisible(true);
    }//GEN-LAST:event_btnProceedToBillingActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String keyword = txtSearch.getText().trim();
        if (keyword.isEmpty()) {
            loadAppointmentData();
            return;
        }

        tableModel.setRowCount(0);
        List<Appointment> list = appointmentDAO.searchAppointments(keyword);
        for (Appointment a : list) {
            tableModel.addRow(new Object[]{
                    a.getAppointmentNo(),
                    a.getPatientId(),
                    a.getPatientName(),
                    a.getDentistName(),
                    a.getTreatmentType(),
                    a.getAppointmentDate(),
                    a.getAppointmentTime(),
                    a.getStatus()
            });
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnResetSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetSearchActionPerformed
        txtSearch.setText("");
        loadAppointmentData();
    }//GEN-LAST:event_btnResetSearchActionPerformed

    private void tblAppointmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAppointmentsMouseClicked
        int row = tblAppointments.getSelectedRow();
        if (row >= 0) {
            txtAppointmentNo.setText(tableModel.getValueAt(row, 0).toString());
            int patId = Integer.parseInt(tableModel.getValueAt(row, 1).toString());
            String dentistName = tableModel.getValueAt(row, 3).toString();
            String treatName = tableModel.getValueAt(row, 4).toString();
            txtDate.setText(tableModel.getValueAt(row, 5).toString());
            cmbTimeSlot.setSelectedItem(tableModel.getValueAt(row, 6).toString());
            cmbStatus.setSelectedItem(tableModel.getValueAt(row, 7).toString());

            for (int i = 0; i < cmbPatient.getItemCount(); i++) {
                Object item = cmbPatient.getItemAt(i);
                if (item instanceof PatientComboItem && ((PatientComboItem) item).id == patId) {
                    cmbPatient.setSelectedIndex(i);
                    break;
                }
            }

            for (int i = 0; i < cmbDentist.getItemCount(); i++) {
                Object item = cmbDentist.getItemAt(i);
                if (item instanceof DentistComboItem && ((DentistComboItem) item).name.equals(dentistName)) {
                    cmbDentist.setSelectedIndex(i);
                    break;
                }
            }

            for (int i = 0; i < cmbTreatment.getItemCount(); i++) {
                Object item = cmbTreatment.getItemAt(i);
                if (item instanceof TreatmentComboItem && ((TreatmentComboItem) item).name.equals(treatName)) {
                    cmbTreatment.setSelectedIndex(i);
                    break;
                }
            }

            updateCostPreview();
        }
    }//GEN-LAST:event_tblAppointmentsMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnProceedToBilling;
    private javax.swing.JButton btnResetSearch;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<Object> cmbDentist;
    private javax.swing.JComboBox<Object> cmbPatient;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JComboBox<String> cmbTimeSlot;
    private javax.swing.JComboBox<Object> cmbTreatment;
    private javax.swing.JPanel formCard;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JScrollPane jScrollPaneNotes;
    private javax.swing.JScrollPane jScrollPaneTable;
    private javax.swing.JLabel lblApptNo;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDentist;
    private javax.swing.JLabel lblEstimatedCost;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblPatient;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTreatment;
    private javax.swing.JPanel tableCard;
    private javax.swing.JTable tblAppointments;
    private javax.swing.JTextArea txaNotes;
    private javax.swing.JTextField txtAppointmentNo;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private static class PatientComboItem {
        int id;
        String name;
        String contact;

        public PatientComboItem(int id, String name, String contact) {
            this.id = id;
            this.name = name;
            this.contact = contact;
        }

        @Override
        public String toString() {
            return name + " (ID: " + id + " | " + contact + ")";
        }
    }

    private static class DentistComboItem {
        String name;
        String spec;
        double consultationFee;

        public DentistComboItem(String name, String spec, double fee) {
            this.name = name;
            this.spec = spec;
            this.consultationFee = fee;
        }

        @Override
        public String toString() {
            return name + " (" + spec + ")";
        }
    }

    private static class TreatmentComboItem {
        String name;
        double cost;

        public TreatmentComboItem(String name, double cost) {
            this.name = name;
            this.cost = cost;
        }

        @Override
        public String toString() {
            return name + " (LKR " + String.format("%.0f", cost) + ")";
        }
    }
}
