package view;

import dao.AppointmentDAO;
import dao.BillDAO;
import dao.DentistDAO;
import model.Appointment;
import model.Bill;
import model.Dentist;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

/**
 * Billing & Patient Receipt Generation GUI Form
 * Fully compatible with NetBeans GUI Builder Design View
 */
public class BillingForm extends javax.swing.JFrame {

    private final BillDAO billDAO = new BillDAO();
    private final AppointmentDAO appointmentDAO = new AppointmentDAO();
    private final DentistDAO dentistDAO = new DentistDAO();
    private final JFrame parentDashboard;

    private DefaultTableModel tableModel;
    private int currentPatientId = 0;
    private int currentBillId = 0;

    public BillingForm() {
        this(null, null);
    }

    public BillingForm(JFrame parentDashboard) {
        this(parentDashboard, null);
    }

    public BillingForm(JFrame parentDashboard, String preSelectedApptNo) {
        this.parentDashboard = parentDashboard;
        initComponents();
        UITheme.setFrameIcon(this);
        UITheme.setStandardWindowSize(this);
        
        // Setup icons
        btnCalculate.setIcon(UITheme.getIcon("calc.png", 16, 16));
        btnSaveBill.setIcon(UITheme.getIcon("add.png", 16, 16));
        btnPrint.setIcon(UITheme.getIcon("print.png", 16, 16));
        btnClear.setIcon(UITheme.getIcon("clear.png", 16, 16));
        btnSearch.setIcon(UITheme.getIcon("search.png", 16, 16));
        btnReset.setIcon(UITheme.getIcon("refresh.png", 16, 16));
        btnBack.setIcon(UITheme.getIcon("back.png", 16, 16));
        
        tableModel = (DefaultTableModel) tblBills.getModel();
        UITheme.styleTable(tblBills);
        loadAppointmentsDropdown();
        loadBillsData();

        if (preSelectedApptNo != null && !preSelectedApptNo.isEmpty()) {
            cmbAppointmentNo.setSelectedItem(preSelectedApptNo);
            onAppointmentSelected();
        }

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                if (parentDashboard != null) {
                    parentDashboard.setVisible(true);
                    if (parentDashboard instanceof Dashboard) {
                        ((Dashboard) parentDashboard).loadDashboardStatistics();
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        formCard = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        lblAppt = new javax.swing.JLabel();
        cmbAppointmentNo = new javax.swing.JComboBox<>();
        lblPatientName = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        lblTreatmentType = new javax.swing.JLabel();
        txtTreatmentType = new javax.swing.JTextField();
        lblTreatmentFee = new javax.swing.JLabel();
        txtTreatmentFee = new javax.swing.JTextField();
        lblConsultFee = new javax.swing.JLabel();
        txtConsultationFee = new javax.swing.JTextField();
        lblDiscountRate = new javax.swing.JLabel();
        cmbDiscountRate = new javax.swing.JComboBox<>();
        lblDiscount = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        txtTotalAmount = new javax.swing.JTextField();
        lblPaymentStatus = new javax.swing.JLabel();
        cmbPaymentStatus = new javax.swing.JComboBox<>();
        btnCalculate = new javax.swing.JButton();
        btnSaveBill = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        receiptCard = new javax.swing.JPanel();
        lblRecTitle = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        jScrollPaneReceipt = new javax.swing.JScrollPane();
        txaReceiptPreview = new javax.swing.JTextArea();
        tableCard = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPaneTable = new javax.swing.JScrollPane();
        tblBills = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sunrise Dental Clinic - Billing & Invoicing");
        setMinimumSize(new java.awt.Dimension(1050, 680));
        setPreferredSize(new java.awt.Dimension(1050, 680));

        headerPanel.setBackground(new java.awt.Color(15, 118, 110));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_48.png"))); // NOI18N

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("PATIENT BILLING & INVOICE RECEIPT");

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnBack.setText("⬅ Back to Dashboard");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitle)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        formCard.setBackground(new java.awt.Color(255, 255, 255));
        formCard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblHeading.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblHeading.setText("Invoice Calculation");

        lblAppt.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblAppt.setText("Appt No *:");

        cmbAppointmentNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAppointmentNoActionPerformed(evt);
            }
        });

        lblPatientName.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblPatientName.setText("Patient Name:");

        txtPatientName.setEditable(false);
        txtPatientName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        lblTreatmentType.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTreatmentType.setText("Treatment:");

        txtTreatmentType.setEditable(false);
        txtTreatmentType.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        lblTreatmentFee.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTreatmentFee.setText("Treatment Fee:");

        txtTreatmentFee.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtTreatmentFee.setText("0.00");

        lblConsultFee.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblConsultFee.setText("Consult. Fee:");

        txtConsultationFee.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtConsultationFee.setText("0.00");

        lblDiscountRate.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblDiscountRate.setText("Discount Rate:");

        cmbDiscountRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDiscountRateActionPerformed(evt);
            }
        });

        lblDiscount.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblDiscount.setText("Discount (LKR):");

        txtDiscount.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtDiscount.setText("0.00");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTotal.setText("Net Total:");

        txtTotalAmount.setEditable(false);
        txtTotalAmount.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txtTotalAmount.setForeground(new java.awt.Color(15, 118, 110));
        txtTotalAmount.setText("0.00");

        lblPaymentStatus.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblPaymentStatus.setText("Status:");

        btnCalculate.setBackground(new java.awt.Color(15, 118, 110));
        btnCalculate.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnCalculate.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculate.setText("⚡ Calculate Total");
        btnCalculate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnSaveBill.setBackground(new java.awt.Color(16, 185, 125));
        btnSaveBill.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSaveBill.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveBill.setText("💾 Save Bill");
        btnSaveBill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaveBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveBillActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formCardLayout = new javax.swing.GroupLayout(formCard);
        formCard.setLayout(formCardLayout);
        formCardLayout.setHorizontalGroup(
            formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formCardLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHeading)
                    .addGroup(formCardLayout.createSequentialGroup()
                        .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAppt)
                            .addComponent(lblPatientName)
                            .addComponent(lblTreatmentType)
                            .addComponent(lblTreatmentFee)
                            .addComponent(lblConsultFee)
                            .addComponent(lblDiscountRate)
                            .addComponent(lblDiscount)
                            .addComponent(lblTotal)
                            .addComponent(lblPaymentStatus))
                        .addGap(18, 18, 18)
                        .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbPaymentStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTotalAmount)
                            .addComponent(txtDiscount)
                            .addComponent(cmbDiscountRate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtConsultationFee)
                            .addComponent(txtTreatmentFee)
                            .addComponent(txtTreatmentType)
                            .addComponent(txtPatientName)
                            .addComponent(cmbAppointmentNo, 0, 210, Short.MAX_VALUE)))
                    .addComponent(btnCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formCardLayout.createSequentialGroup()
                        .addComponent(btnSaveBill, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        formCardLayout.setVerticalGroup(
            formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formCardLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblHeading)
                .addGap(18, 18, 18)
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAppt)
                    .addComponent(cmbAppointmentNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientName)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTreatmentType)
                    .addComponent(txtTreatmentType, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTreatmentFee)
                    .addComponent(txtTreatmentFee, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConsultFee)
                    .addComponent(txtConsultationFee, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiscountRate)
                    .addComponent(cmbDiscountRate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiscount)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaymentStatus)
                    .addComponent(cmbPaymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveBill, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        receiptCard.setBackground(new java.awt.Color(255, 255, 255));
        receiptCard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblRecTitle.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblRecTitle.setText("Receipt Preview");

        btnPrint.setBackground(new java.awt.Color(15, 118, 110));
        btnPrint.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setText("🖨 Print Receipt");
        btnPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        txaReceiptPreview.setEditable(false);
        txaReceiptPreview.setColumns(20);
        txaReceiptPreview.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txaReceiptPreview.setRows(5);
        jScrollPaneReceipt.setViewportView(txaReceiptPreview);

        javax.swing.GroupLayout receiptCardLayout = new javax.swing.GroupLayout(receiptCard);
        receiptCard.setLayout(receiptCardLayout);
        receiptCardLayout.setHorizontalGroup(
            receiptCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, receiptCardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(receiptCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneReceipt)
                    .addGroup(receiptCardLayout.createSequentialGroup()
                        .addComponent(lblRecTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        receiptCardLayout.setVerticalGroup(
            receiptCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receiptCardLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(receiptCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRecTitle)
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        tableCard.setBackground(new java.awt.Color(255, 255, 255));
        tableCard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblSearch.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblSearch.setText("Search Bills:");

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnReset.setText("Reset");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tblBills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill ID", "Appt No", "Patient ID", "Patient Name", "Treatment (LKR)", "Consult (LKR)", "Discount (LKR)", "Total (LKR)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneTable.setViewportView(tblBills);

        javax.swing.GroupLayout tableCardLayout = new javax.swing.GroupLayout(tableCard);
        tableCard.setLayout(tableCardLayout);
        tableCardLayout.setHorizontalGroup(
            tableCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableCardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(tableCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGroup(tableCardLayout.createSequentialGroup()
                        .addComponent(lblSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );
        tableCardLayout.setVerticalGroup(
            tableCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableCardLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(tableCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(formCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(receiptCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(formCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(receiptCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tableCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadAppointmentsDropdown() {
        cmbAppointmentNo.removeAllItems();
        List<Appointment> list = appointmentDAO.getAllAppointments();
        for (Appointment a : list) {
            cmbAppointmentNo.addItem(a.getAppointmentNo());
        }
    }

    private void onAppointmentSelected() {
        String apptNo = (String) cmbAppointmentNo.getSelectedItem();
        if (apptNo == null) return;

        Appointment a = appointmentDAO.getAppointmentByNo(apptNo);
        if (a != null) {
            currentPatientId = a.getPatientId();
            txtPatientName.setText(a.getPatientName());
            txtTreatmentType.setText(a.getTreatmentType());

            double treatCost = dentistDAO.getTreatmentCost(a.getTreatmentType());
            txtTreatmentFee.setText(String.format("%.2f", treatCost));

            Dentist d = dentistDAO.getDentistByName(a.getDentistName());
            double consultFee = d != null ? d.getConsultationFee() : 2000.00;
            txtConsultationFee.setText(String.format("%.2f", consultFee));

            onDiscountRateSelected();
        }
    }

    public void loadBillsData() {
        tableModel.setRowCount(0);
        List<Bill> list = billDAO.getAllBills();
        for (Bill b : list) {
            tableModel.addRow(new Object[]{
                    b.getBillId(),
                    b.getAppointmentNo(),
                    b.getPatientId(),
                    b.getPatientName(),
                    String.format("%.2f", b.getTreatmentFee()),
                    String.format("%.2f", b.getConsultationFee()),
                    String.format("%.2f", b.getDiscount()),
                    String.format("%.2f", b.getTotalAmount())
            });
        }
    }

    private void cmbAppointmentNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAppointmentNoActionPerformed
        onAppointmentSelected();
    }//GEN-LAST:event_cmbAppointmentNoActionPerformed

    private void cmbDiscountRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDiscountRateActionPerformed
        onDiscountRateSelected();
    }//GEN-LAST:event_cmbDiscountRateActionPerformed

    private void onDiscountRateSelected() {
        try {
            double treatFee = Double.parseDouble(txtTreatmentFee.getText().trim());
            double consultFee = Double.parseDouble(txtConsultationFee.getText().trim());
            double subtotal = treatFee + consultFee;

            int index = cmbDiscountRate.getSelectedIndex();
            double discountAmt = 0.0;
            switch (index) {
                case 0: // 0% - No Discount
                    discountAmt = 0.0;
                    txtDiscount.setText("0.00");
                    txtDiscount.setEditable(false);
                    break;
                case 1: // 10% - Promotional
                    discountAmt = subtotal * 0.10;
                    txtDiscount.setText(String.format("%.2f", discountAmt));
                    txtDiscount.setEditable(false);
                    break;
                case 2: // 25% - Senior Citizen
                    discountAmt = subtotal * 0.25;
                    txtDiscount.setText(String.format("%.2f", discountAmt));
                    txtDiscount.setEditable(false);
                    break;
                case 3: // 50% - Staff Welfare
                    discountAmt = subtotal * 0.50;
                    txtDiscount.setText(String.format("%.2f", discountAmt));
                    txtDiscount.setEditable(false);
                    break;
                case 4: // Custom Amount (LKR)
                    txtDiscount.setEditable(true);
                    txtDiscount.requestFocus();
                    break;
            }

            btnCalculateActionPerformed(null);
        } catch (NumberFormatException ignored) {
        }
    }

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        try {
            double treatFee = Double.parseDouble(txtTreatmentFee.getText().trim());
            double consultFee = Double.parseDouble(txtConsultationFee.getText().trim());
            double discount = Double.parseDouble(txtDiscount.getText().trim());

            double subtotal = treatFee + consultFee;
            double discountPercent = subtotal > 0 ? (discount / subtotal) * 100.0 : 0.0;

            // Stored procedure calculation (sp_CalculateBill)
            double total = billDAO.calculateBillProcedure(treatFee, consultFee, discountPercent);
            txtTotalAmount.setText(String.format("%.2f", total));

            generateReceiptPreviewText(treatFee, consultFee, discount, total);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numeric fee amounts!", "Input Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void generateReceiptPreviewText(double treatFee, double consultFee, double discount, double total) {
        String apptNo = (String) cmbAppointmentNo.getSelectedItem();
        String patientName = txtPatientName.getText().trim();
        String treatment = txtTreatmentType.getText().trim();
        String status = (String) cmbPaymentStatus.getSelectedItem();
        String dateStr = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());

        String discountLabel = "Discount Applied";
        int discIdx = cmbDiscountRate.getSelectedIndex();
        if (discIdx == 1) discountLabel = "Discount (10% Promo)";
        else if (discIdx == 2) discountLabel = "Discount (25% Senior)";
        else if (discIdx == 3) discountLabel = "Discount (50% Staff)";
        else if (discIdx == 0) discountLabel = "Discount (0%)";

        StringBuilder sb = new StringBuilder();
        sb.append("=================================================================\n");
        sb.append("                    SUNRISE DENTAL CLINIC                        \n");
        sb.append("         No 45, Galle Road, Colombo 03, Sri Lanka                \n");
        sb.append("           Tel: +94 11 234 5678 | Web: sunrisedental.lk          \n");
        sb.append("=================================================================\n");
        sb.append(String.format(" Receipt Date    : %-30s\n", dateStr));
        sb.append(String.format(" Appointment No  : %-30s\n", apptNo != null ? apptNo : "N/A"));
        sb.append(String.format(" Patient Name    : %-30s (ID: %d)\n", patientName, currentPatientId));
        sb.append(String.format(" Treatment Type  : %-30s\n", treatment));
        sb.append("-----------------------------------------------------------------\n");
        sb.append(String.format(" %-40s : LKR %12.2f\n", "Dental Treatment Fee", treatFee));
        sb.append(String.format(" %-40s : LKR %12.2f\n", "Dentist Consultation Fee", consultFee));
        sb.append("-----------------------------------------------------------------\n");
        sb.append(String.format(" %-40s : LKR %12.2f\n", "Subtotal", treatFee + consultFee));
        sb.append(String.format(" %-40s : LKR %12.2f\n", discountLabel, discount));
        sb.append("=================================================================\n");
        sb.append(String.format(" NET TOTAL PAYABLE                        : LKR %12.2f\n", total));
        sb.append(String.format(" Payment Status                           : %s\n", status));
        sb.append("=================================================================\n");
        sb.append("              Thank you for trusting Sunrise Dental!             \n");
        sb.append("=================================================================\n");

        txaReceiptPreview.setText(sb.toString());
    }

    private void btnSaveBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveBillActionPerformed
        String apptNo = (String) cmbAppointmentNo.getSelectedItem();
        String patientName = txtPatientName.getText().trim();
        String status = (String) cmbPaymentStatus.getSelectedItem();

        if (apptNo == null || patientName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select an appointment before saving!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            double treatFee = Double.parseDouble(txtTreatmentFee.getText().trim());
            double consultFee = Double.parseDouble(txtConsultationFee.getText().trim());
            double discount = Double.parseDouble(txtDiscount.getText().trim());
            double total = Double.parseDouble(txtTotalAmount.getText().trim());

            Bill bill = new Bill(apptNo, currentPatientId, patientName, treatFee, consultFee, discount, total, status);
            boolean success = billDAO.generateBill(bill);

            if (success) {
                JOptionPane.showMessageDialog(this, "Bill record successfully saved for " + apptNo + "!", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadBillsData();
                if (parentDashboard instanceof Dashboard) {
                    ((Dashboard) parentDashboard).loadDashboardStatistics();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Failed to save bill.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid numeric values!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveBillActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtPatientName.setText("");
        txtTreatmentType.setText("");
        txtTreatmentFee.setText("0.00");
        txtConsultationFee.setText("0.00");
        cmbDiscountRate.setSelectedIndex(0);
        txtDiscount.setText("0.00");
        txtTotalAmount.setText("0.00");
        txaReceiptPreview.setText("");
        tblBills.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        if (txaReceiptPreview.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No receipt to print!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            boolean complete = txaReceiptPreview.print();
            if (complete) {
                JOptionPane.showMessageDialog(this, "Receipt sent to printer!", "Print Success", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Printing Error: " + e.getMessage(), "Print Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String keyword = txtSearch.getText().trim();
        if (keyword.isEmpty()) {
            loadBillsData();
            return;
        }

        tableModel.setRowCount(0);
        List<Bill> list = billDAO.searchBills(keyword);
        for (Bill b : list) {
            tableModel.addRow(new Object[]{
                    b.getBillId(),
                    b.getAppointmentNo(),
                    b.getPatientId(),
                    b.getPatientName(),
                    String.format("%.2f", b.getTreatmentFee()),
                    String.format("%.2f", b.getConsultationFee()),
                    String.format("%.2f", b.getDiscount()),
                    String.format("%.2f", b.getTotalAmount())
            });
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtSearch.setText("");
        loadBillsData();
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblBillsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBillsMouseClicked
        int row = tblBills.getSelectedRow();
        if (row >= 0) {
            currentBillId = Integer.parseInt(tableModel.getValueAt(row, 0).toString());
            String apptNo = tableModel.getValueAt(row, 1).toString();
            cmbAppointmentNo.setSelectedItem(apptNo);
            txtPatientName.setText(tableModel.getValueAt(row, 3).toString());
            txtTreatmentFee.setText(tableModel.getValueAt(row, 4).toString());
            txtConsultationFee.setText(tableModel.getValueAt(row, 5).toString());
            txtDiscount.setText(tableModel.getValueAt(row, 6).toString());
            txtTotalAmount.setText(tableModel.getValueAt(row, 7).toString());

            cmbDiscountRate.setSelectedIndex(4); // Custom / exact value from selected bill
            btnCalculateActionPerformed(null);
        }
    }//GEN-LAST:event_tblBillsMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if (parentDashboard != null) {
            parentDashboard.setVisible(true);
            if (parentDashboard instanceof Dashboard) {
                ((Dashboard) parentDashboard).loadDashboardStatistics();
            }
        }
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSaveBill;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbAppointmentNo;
    private javax.swing.JComboBox<String> cmbDiscountRate;
    private javax.swing.JComboBox<String> cmbPaymentStatus;
    private javax.swing.JPanel formCard;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JScrollPane jScrollPaneReceipt;
    private javax.swing.JScrollPane jScrollPaneTable;
    private javax.swing.JLabel lblAppt;
    private javax.swing.JLabel lblConsultFee;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblDiscountRate;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblPaymentStatus;
    private javax.swing.JLabel lblRecTitle;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTreatmentFee;
    private javax.swing.JLabel lblTreatmentType;
    private javax.swing.JPanel receiptCard;
    private javax.swing.JPanel tableCard;
    private javax.swing.JTable tblBills;
    private javax.swing.JTextArea txaReceiptPreview;
    private javax.swing.JTextField txtConsultationFee;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTotalAmount;
    private javax.swing.JTextField txtTreatmentFee;
    private javax.swing.JTextField txtTreatmentType;
    // End of variables declaration//GEN-END:variables
}
