package view;

import dao.AppointmentDAO;
import dao.BillDAO;
import dao.PatientDAO;
import model.Appointment;
import model.User;
import service.ClinicWebService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.util.List;

/**
 * Main Dashboard GUI Form
 * Fully compatible with NetBeans GUI Builder Design View
 */
public class Dashboard extends javax.swing.JFrame {

    private final User currentUser;
    private final PatientDAO patientDAO = new PatientDAO();
    private final AppointmentDAO appointmentDAO = new AppointmentDAO();
    private final BillDAO billDAO = new BillDAO();
    private DefaultTableModel tableModel;

    public Dashboard() {
        this(new User("admin", "", "System Administrator", "Admin", ""));
    }

    public Dashboard(User user) {
        this.currentUser = user != null ? user : new User("admin", "", "System Administrator", "Admin", "");
        initComponents();
        UITheme.setFrameIcon(this);
        UITheme.setStandardWindowSize(this);
        
        // Setup Button Icons
        btnPatients.setIcon(UITheme.getIcon("patient.png", 20, 20));
        btnPatients.setText("Patient Management");
        btnAppointments.setIcon(UITheme.getIcon("appointment.png", 20, 20));
        btnAppointments.setText("Appointment Booking");
        btnBilling.setIcon(UITheme.getIcon("billing.png", 20, 20));
        btnBilling.setText("Billing & Invoicing");
        btnStaffManagement.setIcon(UITheme.getIcon("staff.png", 20, 20));
        btnStaffManagement.setText("Staff Management");
        btnHelp.setIcon(UITheme.getIcon("help.png", 20, 20));
        btnHelp.setText("Help & User Guide");
        btnToggleWebService.setIcon(UITheme.getIcon("web.png", 20, 20));
        btnToggleWebService.setText("Start Web Service");
        btnLogout.setIcon(UITheme.getIcon("logout.png", 20, 20));
        btnLogout.setText("Logout");
        btnRefresh.setIcon(UITheme.getIcon("refresh.png", 16, 16));
        btnRefresh.setText("Refresh");
        
        lblUserGreeting.setIcon(UITheme.getIcon("user.png", 16, 16));
        lblUserGreeting.setText(currentUser.getFullName() + " (" + currentUser.getRole() + ")");
        
        tableModel = (DefaultTableModel) tblRecentAppointments.getModel();
        UITheme.styleTable(tblRecentAppointments);
        
        // Visual indicator for role permissions
        if (!"Admin".equalsIgnoreCase(currentUser.getRole())) {
            btnStaffManagement.setText("Staff (Admin Only)");
        }
        
        loadDashboardStatistics();
        loadRecentAppointments();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblSub = new javax.swing.JLabel();
        lblUserGreeting = new javax.swing.JLabel();
        sidebarPanel = new javax.swing.JPanel();
        btnPatients = new javax.swing.JButton();
        btnAppointments = new javax.swing.JButton();
        btnBilling = new javax.swing.JButton();
        btnStaffManagement = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        btnToggleWebService = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        statsPanel = new javax.swing.JPanel();
        cardPatients = new javax.swing.JPanel();
        lblStatTitle1 = new javax.swing.JLabel();
        lblTotalPatients = new javax.swing.JLabel();
        cardAppointments = new javax.swing.JPanel();
        lblStatTitle2 = new javax.swing.JLabel();
        lblTodayAppointments = new javax.swing.JLabel();
        cardRevenue = new javax.swing.JPanel();
        lblStatTitle3 = new javax.swing.JLabel();
        lblTotalRevenue = new javax.swing.JLabel();
        cardService = new javax.swing.JPanel();
        lblStatTitle4 = new javax.swing.JLabel();
        lblServiceStatus = new javax.swing.JLabel();
        tableCard = new javax.swing.JPanel();
        lblTableTitle = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        jScrollPaneAppt = new javax.swing.JScrollPane();
        tblRecentAppointments = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sunrise Dental Clinic - Management System Dashboard");

        headerPanel.setBackground(new java.awt.Color(15, 118, 110));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_48.png"))); // NOI18N

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("SUNRISE DENTAL CLINIC");

        lblSub.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblSub.setForeground(new java.awt.Color(204, 251, 241));
        lblSub.setText("Colombo Center - Computerized Clinic Management System");

        lblUserGreeting.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblUserGreeting.setForeground(new java.awt.Color(255, 255, 255));
        lblUserGreeting.setText("Staff Member");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(lblSub))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUserGreeting)
                .addGap(25, 25, 25))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitle)
                            .addComponent(lblUserGreeting))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSub)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        sidebarPanel.setBackground(new java.awt.Color(15, 23, 42));

        btnPatients.setBackground(new java.awt.Color(30, 41, 59));
        btnPatients.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnPatients.setForeground(new java.awt.Color(255, 255, 255));
        btnPatients.setText("Patient Management");
        btnPatients.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPatients.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientsActionPerformed(evt);
            }
        });

        btnAppointments.setBackground(new java.awt.Color(30, 41, 59));
        btnAppointments.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnAppointments.setForeground(new java.awt.Color(255, 255, 255));
        btnAppointments.setText("Appointment Booking");
        btnAppointments.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAppointments.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAppointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppointmentsActionPerformed(evt);
            }
        });

        btnBilling.setBackground(new java.awt.Color(30, 41, 59));
        btnBilling.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnBilling.setForeground(new java.awt.Color(255, 255, 255));
        btnBilling.setText("Billing & Invoicing");
        btnBilling.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBilling.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillingActionPerformed(evt);
            }
        });

        btnStaffManagement.setBackground(new java.awt.Color(30, 41, 59));
        btnStaffManagement.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnStaffManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnStaffManagement.setText("Staff Management");
        btnStaffManagement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStaffManagement.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnStaffManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffManagementActionPerformed(evt);
            }
        });

        btnHelp.setBackground(new java.awt.Color(30, 41, 59));
        btnHelp.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnHelp.setForeground(new java.awt.Color(255, 255, 255));
        btnHelp.setText("Help & User Guide");
        btnHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHelp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        btnToggleWebService.setBackground(new java.awt.Color(30, 41, 59));
        btnToggleWebService.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnToggleWebService.setForeground(new java.awt.Color(255, 255, 255));
        btnToggleWebService.setText("Start Web Service");
        btnToggleWebService.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnToggleWebService.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnToggleWebService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToggleWebServiceActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(239, 68, 68));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPatients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAppointments, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(btnBilling, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStaffManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnToggleWebService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBilling, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStaffManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnToggleWebService, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        statsPanel.setOpaque(false);
        statsPanel.setLayout(new java.awt.GridLayout(1, 4, 15, 0));

        cardPatients.setBackground(new java.awt.Color(255, 255, 255));
        cardPatients.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 232, 240), 1, true));

        lblStatTitle1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblStatTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatTitle1.setText("Registered Patients");

        lblTotalPatients.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTotalPatients.setForeground(new java.awt.Color(13, 148, 136));
        lblTotalPatients.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalPatients.setText("0");

        javax.swing.GroupLayout cardPatientsLayout = new javax.swing.GroupLayout(cardPatients);
        cardPatients.setLayout(cardPatientsLayout);
        cardPatientsLayout.setHorizontalGroup(
            cardPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPatientsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalPatients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        cardPatientsLayout.setVerticalGroup(
            cardPatientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardPatientsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblStatTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalPatients)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        statsPanel.add(cardPatients);

        cardAppointments.setBackground(new java.awt.Color(255, 255, 255));
        cardAppointments.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 232, 240), 1, true));

        lblStatTitle2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblStatTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatTitle2.setText("Today's Appointments");

        lblTodayAppointments.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTodayAppointments.setForeground(new java.awt.Color(37, 99, 235));
        lblTodayAppointments.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTodayAppointments.setText("0");

        javax.swing.GroupLayout cardAppointmentsLayout = new javax.swing.GroupLayout(cardAppointments);
        cardAppointments.setLayout(cardAppointmentsLayout);
        cardAppointmentsLayout.setHorizontalGroup(
            cardAppointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAppointmentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardAppointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTodayAppointments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        cardAppointmentsLayout.setVerticalGroup(
            cardAppointmentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardAppointmentsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblStatTitle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTodayAppointments)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        statsPanel.add(cardAppointments);

        cardRevenue.setBackground(new java.awt.Color(255, 255, 255));
        cardRevenue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 232, 240), 1, true));

        lblStatTitle3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblStatTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatTitle3.setText("Total Clinic Revenue");

        lblTotalRevenue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotalRevenue.setForeground(new java.awt.Color(16, 185, 129));
        lblTotalRevenue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalRevenue.setText("LKR 0.00");

        javax.swing.GroupLayout cardRevenueLayout = new javax.swing.GroupLayout(cardRevenue);
        cardRevenue.setLayout(cardRevenueLayout);
        cardRevenueLayout.setHorizontalGroup(
            cardRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardRevenueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatTitle3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        cardRevenueLayout.setVerticalGroup(
            cardRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardRevenueLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblStatTitle3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalRevenue)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        statsPanel.add(cardRevenue);

        cardService.setBackground(new java.awt.Color(255, 255, 255));
        cardService.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 232, 240), 1, true));

        lblStatTitle4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblStatTitle4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatTitle4.setText("REST Web Service");

        lblServiceStatus.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblServiceStatus.setForeground(new java.awt.Color(100, 116, 139));
        lblServiceStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblServiceStatus.setText("Stopped");

        javax.swing.GroupLayout cardServiceLayout = new javax.swing.GroupLayout(cardService);
        cardService.setLayout(cardServiceLayout);
        cardServiceLayout.setHorizontalGroup(
            cardServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardServiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatTitle4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblServiceStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        cardServiceLayout.setVerticalGroup(
            cardServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardServiceLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblStatTitle4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblServiceStatus)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        statsPanel.add(cardService);

        tableCard.setBackground(new java.awt.Color(255, 255, 255));
        tableCard.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(226, 232, 240), 1, true));

        lblTableTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTableTitle.setText("Scheduled Appointments Overview");

        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefresh.setText("🔄 Refresh Data");
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        tblRecentAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Appt No", "Patient Name", "Dentist", "Treatment", "Date", "Time", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneAppt.setViewportView(tblRecentAppointments);

        javax.swing.GroupLayout tableCardLayout = new javax.swing.GroupLayout(tableCard);
        tableCard.setLayout(tableCardLayout);
        tableCardLayout.setHorizontalGroup(
            tableCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableCardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(tableCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneAppt, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGroup(tableCardLayout.createSequentialGroup()
                        .addComponent(lblTableTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        tableCardLayout.setVerticalGroup(
            tableCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableCardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(tableCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTableTitle)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneAppt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(statsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tableCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void loadDashboardStatistics() {
        int totalPatients = patientDAO.getTotalPatientCount();
        int todayAppts = appointmentDAO.getTodayAppointmentsCount();
        double totalRev = billDAO.getTotalRevenue();

        lblTotalPatients.setText(String.valueOf(totalPatients));
        lblTodayAppointments.setText(String.valueOf(todayAppts));
        lblTotalRevenue.setText("LKR " + String.format("%,.2f", totalRev));

        if (ClinicWebService.isRunning()) {
            lblServiceStatus.setText("● Active");
            lblServiceStatus.setForeground(new java.awt.Color(16, 185, 129));
            btnToggleWebService.setText("🌐 Stop Web Service");
        } else {
            lblServiceStatus.setText("○ Stopped");
            lblServiceStatus.setForeground(new java.awt.Color(100, 116, 139));
            btnToggleWebService.setText("🌐 Start Web Service");
        }
    }

    public void loadRecentAppointments() {
        tableModel.setRowCount(0);
        List<Appointment> list = appointmentDAO.getAllAppointments();
        for (Appointment a : list) {
            tableModel.addRow(new Object[]{
                    a.getAppointmentNo(),
                    a.getPatientName(),
                    a.getDentistName(),
                    a.getTreatmentType(),
                    a.getAppointmentDate(),
                    a.getAppointmentTime(),
                    a.getStatus()
            });
        }
    }

    private void btnPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientsActionPerformed
        PatientForm patientForm = new PatientForm(this);
        patientForm.setVisible(true);
    }//GEN-LAST:event_btnPatientsActionPerformed

    private void btnAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointmentsActionPerformed
        AppointmentForm appointmentForm = new AppointmentForm(this);
        appointmentForm.setVisible(true);
    }//GEN-LAST:event_btnAppointmentsActionPerformed

    private void btnBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillingActionPerformed
        BillingForm billingForm = new BillingForm(this);
        billingForm.setVisible(true);
    }//GEN-LAST:event_btnBillingActionPerformed

    private void btnStaffManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffManagementActionPerformed
        if (!"Admin".equalsIgnoreCase(currentUser.getRole())) {
            JOptionPane.showMessageDialog(this,
                    "Access Denied: Only users with the 'Admin' role can manage staff accounts.\n" +
                    "Your current role is: " + currentUser.getRole(),
                    "Admin Permission Required",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        AdminStaffForm adminForm = new AdminStaffForm(this);
        adminForm.setVisible(true);
    }//GEN-LAST:event_btnStaffManagementActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        HelpDialog helpDialog = new HelpDialog(this);
        helpDialog.setVisible(true);
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnToggleWebServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToggleWebServiceActionPerformed
        if (ClinicWebService.isRunning()) {
            ClinicWebService.stopServer();
            JOptionPane.showMessageDialog(this, "Clinic REST Web Service has been stopped.", "Web Service Offline", JOptionPane.INFORMATION_MESSAGE);
        } else {
            ClinicWebService.startServer();
            JOptionPane.showMessageDialog(this,
                    "Clinic REST Web Service is now running!\n\n" +
                    "Available Endpoints:\n" +
                    "• http://localhost:8088/api/status\n" +
                    "• http://localhost:8088/api/appointments\n" +
                    "• http://localhost:8088/api/appointment?no=APT-1001\n" +
                    "• http://localhost:8088/api/dentists\n" +
                    "• http://localhost:8088/api/treatments",
                    "Web Service Active",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        loadDashboardStatistics();
    }//GEN-LAST:event_btnToggleWebServiceActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?", "Confirm Logout", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose();
            new LoginForm().setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadDashboardStatistics();
        loadRecentAppointments();
    }//GEN-LAST:event_btnRefreshActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppointments;
    private javax.swing.JButton btnBilling;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPatients;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnStaffManagement;
    private javax.swing.JButton btnToggleWebService;
    private javax.swing.JPanel cardAppointments;
    private javax.swing.JPanel cardPatients;
    private javax.swing.JPanel cardRevenue;
    private javax.swing.JPanel cardService;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JScrollPane jScrollPaneAppt;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblServiceStatus;
    private javax.swing.JLabel lblStatTitle1;
    private javax.swing.JLabel lblStatTitle2;
    private javax.swing.JLabel lblStatTitle3;
    private javax.swing.JLabel lblStatTitle4;
    private javax.swing.JLabel lblSub;
    private javax.swing.JLabel lblTableTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTodayAppointments;
    private javax.swing.JLabel lblTotalPatients;
    private javax.swing.JLabel lblTotalRevenue;
    private javax.swing.JLabel lblUserGreeting;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JPanel statsPanel;
    private javax.swing.JPanel tableCard;
    private javax.swing.JTable tblRecentAppointments;
    // End of variables declaration//GEN-END:variables
}
