package view;

import dao.AppointmentDAO;
import dao.DentistDAO;
import model.Appointment;
import model.User;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.Map;

/**
 * Dentist Dashboard for Doctor Consultation & Patient Feedback
 * Fully compatible with NetBeans GUI Builder Design View
 */
public class DentistDashboard extends javax.swing.JFrame {

    private final User currentDentist;
    private final AppointmentDAO appointmentDAO = new AppointmentDAO();
    private final DentistDAO dentistDAO = new DentistDAO();
    private DefaultTableModel tableModel;
    private String selectedAppointmentNo = "";
    private int selectedPatientId = 0;

    public DentistDashboard() {
        this(new User("drpriyanga", "", "Dr. Priyanga Jayawardena", "Dentist", "0761122334"));
    }

    public DentistDashboard(User dentistUser) {
        this.currentDentist = dentistUser != null ? dentistUser : new User("drpriyanga", "", "Dr. Priyanga Jayawardena", "Dentist", "");
        initComponents();
        UITheme.setFrameIcon(this);
        
        lblDoctorGreeting.setText("Attending Doctor: " + currentDentist.getFullName() + " (" + currentDentist.getRole() + ")");
        
        // Setup icons
        btnSaveFeedback.setIcon(UITheme.getIcon("add.png", 16, 16));
        btnClear.setIcon(UITheme.getIcon("clear.png", 16, 16));
        btnRefresh.setIcon(UITheme.getIcon("refresh.png", 16, 16));
        btnLogout.setIcon(UITheme.getIcon("logout.png", 16, 16));
        btnHelp.setIcon(UITheme.getIcon("help.png", 16, 16));
        
        tableModel = (DefaultTableModel) tblDoctorAppointments.getModel();
        UITheme.styleTable(tblDoctorAppointments);
        loadTreatmentRecommendations();
        loadDoctorSchedule();
    }

    private void loadTreatmentRecommendations() {
        cmbRecommendedTreatment.removeAllItems();
        cmbRecommendedTreatment.addItem("-- No Future Treatment Required --");
        Map<String, Double> treatments = dentistDAO.getAllTreatmentsWithCosts();
        for (String treat : treatments.keySet()) {
            cmbRecommendedTreatment.addItem(treat);
        }
    }

    private void loadDoctorSchedule() {
        tableModel.setRowCount(0);
        String doctorName = currentDentist.getFullName();
        List<Appointment> list = appointmentDAO.getAppointmentsByDentist(doctorName);
        
        // Fallback: If no direct doctor match, load all active appointments
        if (list.isEmpty()) {
            list = appointmentDAO.getAllAppointments();
        }

        for (Appointment a : list) {
            tableModel.addRow(new Object[]{
                    a.getAppointmentNo(),
                    a.getPatientId(),
                    a.getPatientName(),
                    a.getTreatmentType(),
                    a.getAppointmentDate(),
                    a.getAppointmentTime(),
                    a.getStatus()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblDoctorGreeting = new javax.swing.JLabel();
        btnHelp = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        tableCard = new javax.swing.JPanel();
        lblTableTitle = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        jScrollPaneTable = new javax.swing.JScrollPane();
        tblDoctorAppointments = new javax.swing.JTable();
        formCard = new javax.swing.JPanel();
        lblFormTitle = new javax.swing.JLabel();
        lblSelectedAppt = new javax.swing.JLabel();
        lblSelectedPatient = new javax.swing.JLabel();
        lblDiagnosis = new javax.swing.JLabel();
        jScrollPaneDiag = new javax.swing.JScrollPane();
        txaDiagnosis = new javax.swing.JTextArea();
        lblRecommendedTreatment = new javax.swing.JLabel();
        cmbRecommendedTreatment = new javax.swing.JComboBox<>();
        lblFollowUp = new javax.swing.JLabel();
        cmbFollowUp = new javax.swing.JComboBox<>();
        btnSaveFeedback = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sunrise Dental Clinic - Dentist Consultation & Clinical Portal");
        setMinimumSize(new java.awt.Dimension(1050, 680));
        setPreferredSize(new java.awt.Dimension(1050, 680));

        headerPanel.setBackground(new java.awt.Color(15, 118, 110));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_48.png"))); // NOI18N

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("DOCTOR CLINICAL CONSULTATION PORTAL");

        lblDoctorGreeting.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblDoctorGreeting.setForeground(new java.awt.Color(204, 251, 241));
        lblDoctorGreeting.setText("Attending Doctor Portal");

        btnHelp.setBackground(new java.awt.Color(13, 148, 136));
        btnHelp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHelp.setForeground(new java.awt.Color(255, 255, 255));
        btnHelp.setText("Help Guide");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(239, 68, 68));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(lblDoctorGreeting))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDoctorGreeting))
                    .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        tableCard.setBackground(new java.awt.Color(255, 255, 255));
        tableCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 232, 240)));

        lblTableTitle.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblTableTitle.setForeground(new java.awt.Color(15, 23, 42));
        lblTableTitle.setText("Today's Patient Appointment Queue");

        btnRefresh.setBackground(new java.awt.Color(15, 118, 110));
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh List");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        tblDoctorAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Appt No", "Patient ID", "Patient Name", "Treatment", "Date", "Time", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDoctorAppointments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDoctorAppointmentsMouseClicked(evt);
            }
        });
        jScrollPaneTable.setViewportView(tblDoctorAppointments);

        javax.swing.GroupLayout tableCardLayout = new javax.swing.GroupLayout(tableCard);
        tableCard.setLayout(tableCardLayout);
        tableCardLayout.setHorizontalGroup(
            tableCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableCardLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(tableCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tableCardLayout.createSequentialGroup()
                        .addComponent(lblTableTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        tableCardLayout.setVerticalGroup(
            tableCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableCardLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(tableCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTableTitle)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        formCard.setBackground(new java.awt.Color(255, 255, 255));
        formCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 232, 240)));

        lblFormTitle.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblFormTitle.setForeground(new java.awt.Color(15, 23, 42));
        lblFormTitle.setText("Clinical Diagnosis & Treatment Recommendation");

        lblSelectedAppt.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblSelectedAppt.setForeground(new java.awt.Color(15, 118, 110));
        lblSelectedAppt.setText("Selected Appointment: None Selected");

        lblSelectedPatient.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblSelectedPatient.setForeground(new java.awt.Color(71, 85, 105));
        lblSelectedPatient.setText("Patient: Please select an appointment from the left table.");

        lblDiagnosis.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDiagnosis.setForeground(new java.awt.Color(15, 23, 42));
        lblDiagnosis.setText("Clinical Observations & Diagnosis Notes:");

        txaDiagnosis.setColumns(20);
        txaDiagnosis.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txaDiagnosis.setLineWrap(true);
        txaDiagnosis.setRows(4);
        txaDiagnosis.setWrapStyleWord(true);
        jScrollPaneDiag.setViewportView(txaDiagnosis);

        lblRecommendedTreatment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRecommendedTreatment.setForeground(new java.awt.Color(15, 23, 42));
        lblRecommendedTreatment.setText("Recommended Future Treatment:");

        cmbRecommendedTreatment.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        lblFollowUp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFollowUp.setForeground(new java.awt.Color(15, 23, 42));
        lblFollowUp.setText("Suggested Follow-up Timing:");

        cmbFollowUp.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cmbFollowUp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Follow-up Needed (Completed)", "Within 1 Week (Urgent Follow-up)", "Within 2 Weeks (Routine Treatment)", "Within 1 Month (Review)", "Routine Dental Checkup in 6 Months" }));

        btnSaveFeedback.setBackground(new java.awt.Color(16, 185, 129));
        btnSaveFeedback.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSaveFeedback.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveFeedback.setText("Save Consultation & Complete");
        btnSaveFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveFeedbackActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(100, 116, 139));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear Notes");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formCardLayout = new javax.swing.GroupLayout(formCard);
        formCard.setLayout(formCardLayout);
        formCardLayout.setHorizontalGroup(
            formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formCardLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneDiag)
                    .addComponent(cmbRecommendedTreatment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbFollowUp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formCardLayout.createSequentialGroup()
                        .addComponent(btnSaveFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formCardLayout.createSequentialGroup()
                        .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFormTitle)
                            .addComponent(lblSelectedAppt)
                            .addComponent(lblSelectedPatient)
                            .addComponent(lblDiagnosis)
                            .addComponent(lblRecommendedTreatment)
                            .addComponent(lblFollowUp))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );
        formCardLayout.setVerticalGroup(
            formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formCardLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblFormTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSelectedAppt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSelectedPatient)
                .addGap(18, 18, 18)
                .addComponent(lblDiagnosis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneDiag, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRecommendedTreatment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbRecommendedTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFollowUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbFollowUp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(formCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tableCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(formCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tableCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        new HelpDialog(this).setVisible(true);
    }//GEN-LAST:event_btnHelpActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int choice = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out of Doctor Portal?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            this.dispose();
            new LoginForm().setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadDoctorSchedule();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tblDoctorAppointmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDoctorAppointmentsMouseClicked
        int row = tblDoctorAppointments.getSelectedRow();
        if (row >= 0) {
            selectedAppointmentNo = tableModel.getValueAt(row, 0).toString();
            selectedPatientId = Integer.parseInt(tableModel.getValueAt(row, 1).toString());
            String patientName = tableModel.getValueAt(row, 2).toString();
            String currentTreatment = tableModel.getValueAt(row, 3).toString();

            lblSelectedAppt.setText("Selected Appointment: " + selectedAppointmentNo + " (" + currentTreatment + ")");
            lblSelectedPatient.setText("Patient: " + patientName + " (Patient ID: " + selectedPatientId + ")");

            Appointment appt = appointmentDAO.getAppointmentByNo(selectedAppointmentNo);
            if (appt != null) {
                txaDiagnosis.setText(appt.getDiagnosis() != null ? appt.getDiagnosis() : "");
                if (appt.getRecommendedTreatment() != null && !appt.getRecommendedTreatment().isEmpty()) {
                    cmbRecommendedTreatment.setSelectedItem(appt.getRecommendedTreatment());
                } else {
                    cmbRecommendedTreatment.setSelectedIndex(0);
                }
                if (appt.getFollowUpAdvice() != null && !appt.getFollowUpAdvice().isEmpty()) {
                    cmbFollowUp.setSelectedItem(appt.getFollowUpAdvice());
                } else {
                    cmbFollowUp.setSelectedIndex(0);
                }
            }
        }
    }//GEN-LAST:event_tblDoctorAppointmentsMouseClicked

    private void btnSaveFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveFeedbackActionPerformed
        if (selectedAppointmentNo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select an appointment from the left queue first!", "Selection Required", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String diagnosis = txaDiagnosis.getText().trim();
        String recommendedTreatment = cmbRecommendedTreatment.getSelectedIndex() > 0 ? (String) cmbRecommendedTreatment.getSelectedItem() : "";
        String followUp = (String) cmbFollowUp.getSelectedItem();

        if (diagnosis.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter clinical observations / diagnosis notes before saving!", "Validation Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean success = appointmentDAO.saveDentistFeedback(selectedAppointmentNo, diagnosis, recommendedTreatment, followUp);
        if (success) {
            JOptionPane.showMessageDialog(this,
                    "Consultation feedback successfully recorded for " + selectedAppointmentNo + "!\n" +
                    "Status marked as Completed.\n" +
                    "Front-desk staff can now view future recommendations for this patient.",
                    "Clinical Feedback Saved",
                    JOptionPane.INFORMATION_MESSAGE);
            loadDoctorSchedule();
            clearForm();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to save consultation feedback.", "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveFeedbackActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void clearForm() {
        selectedAppointmentNo = "";
        selectedPatientId = 0;
        lblSelectedAppt.setText("Selected Appointment: None Selected");
        lblSelectedPatient.setText("Patient: Please select an appointment from the left table.");
        txaDiagnosis.setText("");
        cmbRecommendedTreatment.setSelectedIndex(0);
        cmbFollowUp.setSelectedIndex(0);
        tblDoctorAppointments.clearSelection();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSaveFeedback;
    private javax.swing.JComboBox<String> cmbFollowUp;
    private javax.swing.JComboBox<String> cmbRecommendedTreatment;
    private javax.swing.JPanel formCard;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JScrollPane jScrollPaneDiag;
    private javax.swing.JScrollPane jScrollPaneTable;
    private javax.swing.JLabel lblDiagnosis;
    private javax.swing.JLabel lblDoctorGreeting;
    private javax.swing.JLabel lblFollowUp;
    private javax.swing.JLabel lblFormTitle;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblRecommendedTreatment;
    private javax.swing.JLabel lblSelectedAppt;
    private javax.swing.JLabel lblSelectedPatient;
    private javax.swing.JLabel lblTableTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel tableCard;
    private javax.swing.JTable tblDoctorAppointments;
    private javax.swing.JTextArea txaDiagnosis;
    // End of variables declaration//GEN-END:variables
}
