package view;

import java.awt.event.ActionEvent;

/**
 * Help & User Guide Dialog (Assignment Brief Requirement 5)
 * Fully compatible with NetBeans GUI Builder Design View
 */
public class HelpDialog extends javax.swing.JDialog {

    public HelpDialog(java.awt.Frame parent) {
        super(parent, "Sunrise Dental Clinic - User Guide & Instructions", true);
        initComponents();
        btnClose.setIcon(UITheme.getIcon("back.png", 16, 16));
        txtHelp.setText(getHelpHtmlContent());
        txtHelp.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jScrollPaneHelp = new javax.swing.JScrollPane();
        txtHelp = new javax.swing.JTextPane();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sunrise Dental Clinic - User Guide & Instructions");
        setModal(true);

        headerPanel.setBackground(new java.awt.Color(15, 118, 110));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_48.png"))); // NOI18N

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("STAFF USER GUIDE & HELP MANUAL");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTitle)
                .addContainerGap(300, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblTitle)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        txtHelp.setEditable(false);
        txtHelp.setContentType("text/html"); // NOI18N
        txtHelp.setText("<html><body style='font-family:Segoe UI, sans-serif; font-size:12px; color:#1e293b; padding:10px;'><h2 style='color:#0f766e;'>Welcome to Sunrise Dental Clinic</h2><p>This computerized system streamlines patient records, appointment scheduling, billing, and distributed services.</p><hr/><h3 style='color:#0f766e;'>1. Authentication</h3><p>Enter username and password (admin / admin123 or receptionist / staff123).</p><h3 style='color:#0f766e;'>2. Patients</h3><p>Add, edit, delete, and search patient details.</p><h3 style='color:#0f766e;'>3. Appointments</h3><p>Select patient, doctor, treatment, date and time slot. Prevents double-booking automatically.</p><h3 style='color:#0f766e;'>4. Billing</h3><p>Calculates treatment and consultation charges with discount and prints official receipts.</p></body></html>");
        jScrollPaneHelp.setViewportView(txtHelp);

        btnClose.setBackground(new java.awt.Color(15, 118, 110));
        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("Close Guide");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneHelp)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneHelp, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private String getHelpHtmlContent() {
        return "<html><body style='font-family:Segoe UI, sans-serif; font-size:12px; color:#1e293b; padding:10px;'>" +
                "<h2 style='color:#0f766e;'>Welcome to Sunrise Dental Clinic Management System</h2>" +
                "<p>This computerized system streamlines patient records, appointment scheduling, billing, and distributed services.</p>" +
                "<hr color='#cbd5e1'/>" +
                
                "<h3 style='color:#0f766e;'>1. System Authentication (Login & Signup)</h3>" +
                "<ul>" +
                "<li><b>Existing Staff:</b> Enter your registered username and password to log in.</li>" +
                "<li><b>Default Credentials:</b> Admin (<code>admin / admin123</code>), Receptionist (<code>receptionist / staff123</code>).</li>" +
                "<li><b>New Staff Registration:</b> Click 'Register', fill in required details, valid 10-digit Sri Lankan phone number, and select role.</li>" +
                "</ul>" +

                "<h3 style='color:#0f766e;'>2. Patient Management (Register & Manage Records)</h3>" +
                "<ul>" +
                "<li>Click <b>'Patient Management'</b> from the dashboard.</li>" +
                "<li>To register a new patient: Enter Full Name, Contact No (e.g. 0771234567), Address, and optional Medical History (e.g. allergies, diabetes), then click <b>'Save'</b>.</li>" +
                "<li>To update: Click any row in the table, modify details, and click <b>'Update'</b>.</li>" +
                "<li>To delete: Select the row and click <b>'Delete'</b>.</li>" +
                "<li>Use the search bar at the top right to filter patients by name, contact, or address.</li>" +
                "</ul>" +

                "<h3 style='color:#0f766e;'>3. Appointment Scheduling & Double-Booking Prevention</h3>" +
                "<ul>" +
                "<li>Click <b>'Appointment Booking'</b> from the dashboard.</li>" +
                "<li>Select the registered patient, dentist, treatment type, appointment date, and time slot.</li>" +
                "<li>The system automatically computes and displays the estimated treatment and consultation fees.</li>" +
                "<li><b>Double-Booking Check:</b> The system will prevent booking if the chosen dentist is already scheduled for that exact time slot.</li>" +
                "<li>Click <b>'Book'</b> to confirm. Click <b>'Proceed to Billing'</b> to immediately generate an invoice.</li>" +
                "</ul>" +

                "<h3 style='color:#0f766e;'>4. Calculate & Print Bills / Receipts</h3>" +
                "<ul>" +
                "<li>Click <b>'Billing & Invoicing'</b>.</li>" +
                "<li>Select the appointment number from the dropdown to load the patient and treatment information automatically.</li>" +
                "<li>Enter any applicable discount amount and click <b>'Calculate Total'</b>.</li>" +
                "<li>Click <b>'Save Bill'</b> to store the payment record.</li>" +
                "<li>Click <b>'Print Receipt'</b> to send the formatted clinic invoice directly to your printer or save as PDF.</li>" +
                "</ul>" +

                "<h3 style='color:#0f766e;'>5. Distributed Web Services (REST API)</h3>" +
                "<ul>" +
                "<li>On the dashboard, click <b>'Start Web Service'</b> to host the lightweight remote REST API on <code>http://localhost:8088/api/</code>.</li>" +
                "<li>Remote clients or branches can query appointment status via <code>/api/appointments</code> and <code>/api/appointment?no=APT-1001</code>.</li>" +
                "</ul>" +

                "<h3 style='color:#0f766e;'>6. Database & WAMP/XAMPP Server Troubleshooting</h3>" +
                "<ul>" +
                "<li>Ensure MySQL is running on port 3306.</li>" +
                "<li>Open <b>http://localhost/phpmyadmin</b> and verify <code>clinic_db</code> is imported.</li>" +
                "<li>Run <code>TestConnection.java</code> from the <code>db</code> package for automated diagnostics.</li>" +
                "</ul>" +
                "<br/>" +
                "<p style='color:#64748b; font-size:11px;'>Sunrise Dental Clinic Management System © 2026. All rights reserved.</p>" +
                "</body></html>";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JScrollPane jScrollPaneHelp;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextPane txtHelp;
    // End of variables declaration//GEN-END:variables
}
